version: "3.9"

services:
  sae-enfermagem:
    build:
      context: .
      dockerfile: Dockerfile-python-gunicorn
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      - DJANGO_SETTINGS_MODULE=SAE.settings
    volumes:
      - static_volume:/sae-enfermagem-django/static
      - media_volume:/sae-enfermagem-django/media
    networks:
      - sae-network

volumes:
  static_volume:
  media_volume:

networks:
  sae-network:
    driver: bridge