#version: "3.9"

services:
  sae-enfermagem:
    build:
      context: .
      dockerfile: Dockerfile-python-gunicorn
    command: gunicorn SAE.wsgi --bind 0.0.0.0:80 --reload
    restart: unless-stopped
    volumes:
      - ../sae-enfermagem-django:/sae-enfermagem-django

    expose:
      - 8002
    ports:
      - 8002:80

    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
    # external: true



#    django-uwsgi:
    #    build:
    #      context: .
    #      dockerfile: Dockerfile-python
    #
    #    command: uwsgi --http 0.0.0.0:8002 --module hospital.wsgi
    #    expose:
    #      - 8002
    #    ports:
    #      - 8002:8002