# Generated by Django 4.2.2 on 2023-06-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parto', models.CharField(max_length=100)),
                ('data_parto', models.DateField()),
                ('hora_parto', models.TimeField()),
                ('g', models.IntegerField()),
                ('p', models.IntegerField()),
                ('a', models.IntegerField()),
                ('ig', models.IntegerField()),
                ('hd', models.IntegerField()),
                ('admissao_acompanhente_livre_escolha', models.BooleanField()),
                ('n_filhos_vivos', models.IntegerField()),
                ('n_consultas_prenatl', models.IntegerField()),
                ('internacao_rn', models.BooleanField()),
                ('venoclise', models.CharField(max_length=100)),
                ('venoclise_tipo', models.CharField(max_length=100)),
                ('sinais_flogistico', models.BooleanField()),
                ('alergias', models.CharField(max_length=100)),
                ('patologias', models.CharField(max_length=100)),
                ('queixas', models.CharField(max_length=100)),
                ('queixas_qual', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario0301',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questionario03', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario03')),
            ],
        ),
    ]
