# Generated by Django 4.2.2 on 2023-06-25 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario03',
            name='data_atualizacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionario03',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='ap',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='batimentos_cardiacos',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='respiracao',
            field=models.CharField(choices=[('Eupneica', 'Eupneica'), ('Taquipneica', 'Taquipneica'), ('Dispneica', 'Dispneica'), ('Bradipneica', 'Bradipneica')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='a',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='admissao_acompanhente_livre_escolha',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='alergias',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='data_parto',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='g',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='hd',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='hora_parto',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='ig',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='internacao_rn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='n_consultas_prenatl',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='n_filhos_vivos',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='p',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='patologias',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='queixas',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='queixas_qual',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='sinais_flogistico',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='tipo_parto',
            field=models.CharField(choices=[('PPN', 'PPN'), ('POC', 'POC'), ('Fórceps.', 'Fórceps.')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='venoclise',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='venoclise_tipo',
            field=models.CharField(choices=[('MSD', 'MSD'), ('MSE', 'MSE')], default='', max_length=50),
        ),
    ]
