# Generated by Django 4.2.2 on 2023-06-25 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_remove_questionario03_n_consultas_prenatl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario0301',
            name='abdome',
            field=models.CharField(choices=[('Normotenso e flácio', 'Normotenso e flácio'), ('Globoso', 'Globoso'), ('Distendido', 'Distendido'), ('Doloroso', 'Doloroso')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='aceita_dieta_oferecida',
            field=models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial'), ('Não aceita', 'Não aceita'), ('Zero', 'Zero')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='data_atualizacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='diurese',
            field=models.CharField(choices=[('Espontânea', 'Espontânea'), ('CVD', 'CVD'), ('CVA', 'CVA')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='diurese_cracteristicas',
            field=models.CharField(default='', max_length=100, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='evacuacoes',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='evacuacoes_n_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='pressao_arterial',
            field=models.CharField(choices=[('Normotenso', 'Normotenso'), ('Hipotenso', 'Hipotenso'), ('Hipertenso', 'Hipertenso')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='internacao_rn',
            field=models.CharField(default='', max_length=50, verbose_name='Internação do RN'),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='sinais_flogistico',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='', max_length=3, verbose_name='Sinais Flogísticos'),
        ),
        migrations.AlterField(
            model_name='questionario03',
            name='venoclise_tipo',
            field=models.CharField(choices=[('MSD', 'MSD'), ('MSE', 'MSE')], default='', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='questionario0301',
            name='ap',
            field=models.CharField(choices=[('MV', 'MV'), ('RA', 'RA')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionario0301',
            name='batimentos_cardiacos',
            field=models.CharField(choices=[('Normocárdica', 'Normocárdica'), ('Bradicárdica', 'Bradicárdica'), ('Taquicárdica', 'Taquicárdica')], default='', max_length=200),
        ),
    ]
