# Generated by Django 4.2.2 on 2023-06-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0005_questionario0301_abdome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario0301',
            old_name='Questionario03',
            new_name='questionario03',
        ),
    ]
