# Generated by Django 4.2.2 on 2023-06-28 12:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0006_rename_questionario03_questionario0301_questionario03'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario0302',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguranca_emocional', multiselectfield.db.fields.MultiSelectField(choices=[('alterações de humor', 'Alterações de Humor'), ('Crises de Choro', 'Crises de Choro'), ('Emotividade Exacerbada', 'Emotividade Exacerbada'), ('Insegurança', 'Insegurança'), ('Irritabilidade', 'Irritabilidade'), ('Tristeza', 'Tristeza'), ('Alegria', 'Alegria'), ('Medo', 'Medo'), ('Ansiedade', 'Ansiedade')], default='', max_length=30)),
                ('amor_aceitacao', models.CharField(choices=[('carência afetiva', 'Carência Afetiva'), ('desinteresse pelo RN', 'desinteresse pelo RN'), ('Acompanhante', 'Acompanhante')], default='', max_length=30)),
                ('amor_aceitacao_apoio_familiar', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='', max_length=30, verbose_name='Apoio Familiar')),
                ('amor_aceitacao_acompanhante', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='', max_length=30, verbose_name='Acompanhante')),
                ('amor_aceitacao_acompanhante_quem', models.CharField(default='', max_length=30, verbose_name='Quem')),
                ('aprendizagem_educacao_saude', models.CharField(choices=[('Dúvidas sobre o autocuidado', 'Dúvidas sobre o autocuidado'), ('Dificuldade em compreender o regime terapêutico', 'Dificuldade em compreender o regime terapêutico'), ('Dúvidas sobre o período pós-parto', 'Dúvidas sobre o período pós-parto'), ('Dúvidas sobre aleitamento materno', 'Dúvidas sobre aleitamento materno'), ('Dificuldades na ordenha de leite materno', 'Dificuldades na ordenha de leite materno'), ('Dúvidas/dificuldades nos cuidados com o RN', 'Dúvidas/dificuldades nos cuidados com o RN')], default='', max_length=50)),
                ('comunicacao_gregaria', models.CharField(choices=[('boa interação familiar', 'boa interação familiar'), ('conflito familiar', 'conflito familiar'), ('isolamento', 'isolamento'), ('recebe visitas', 'recebe visitas'), ('gravidez desejada', 'gravidez desejada'), ('gravidez indesejada', 'gravidez indesejada')], default='', max_length=30)),
                ('percepcao_sobre_imagem_corporal', models.CharField(choices=[('satisfeita', 'satisfeita'), ('insatisfeita', 'insatisfeita')], default='', max_length=30)),
                ('autoconfianca_como_mae', models.CharField(choices=[('satisfeita', 'satisfeita'), ('insatisfeita', 'insatisfeita')], default='', max_length=30)),
                ('religiao', models.CharField(default='', max_length=30, verbose_name='Religião')),
                ('necessita_auxilio_espiritual', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='', max_length=30, verbose_name='Necessita de auxílio espiritual')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario0303',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_liquidos_deficiente', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='', max_length=30, verbose_name='Volume de Líquidos Deficiente')),
                ('volume_liquidos_deficiente_intervencoes_enfermagem', models.CharField(default='', max_length=30, verbose_name='Intervenções de Enfermagem')),
                ('volume_liquidos_deficiente_avaliacao', models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30, verbose_name='Avaliação')),
            ],
        ),
        migrations.RenameField(
            model_name='questionario0301',
            old_name='diurese_cracteristicas',
            new_name='diurese_caracteristicas',
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='amamentacao',
            field=models.CharField(choices=[('Satisfatória', 'Satisfatória'), ('Dificuldades', 'Dificuldades'), ('Dor', 'Dor'), ('Pega', 'Pega'), ('Sucção', 'Sucção'), ('Ordenha manual', 'Ordenha manual')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='amamentacao_motivos',
            field=models.CharField(default='', max_length=30, verbose_name='Motivos'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='atura',
            field=models.CharField(default='', max_length=30, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='colostro_expresssao',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Diminuído', 'Diminuído')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='exames_alterados',
            field=models.CharField(default='', max_length=30, verbose_name='Exames Alterados'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='fc',
            field=models.CharField(default='', max_length=30, verbose_name='FC'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='hgt',
            field=models.CharField(default='', max_length=30, verbose_name='HGT'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='higiene',
            field=models.CharField(choices=[('Preservada', 'Preservada'), ('Alterada', 'Alterada')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='inicisao_cirurgica',
            field=models.CharField(choices=[('curativo oclusivo', 'curativo oclusivo'), ('limpa e seca', 'limpa e seca'), ('Com sinais flogísticos', 'Com sinais flogísticos')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='inicisao_cirurgica_quais',
            field=models.CharField(default='', max_length=30, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='involucao_uterina',
            field=models.CharField(choices=[('acima da CU', 'acima da CU'), ('à altura da CU', 'à altura da CU'), ('abaixo da CU', 'abaixo da CU')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='involucao_uterina_acima_cu',
            field=models.CharField(default='', max_length=30, verbose_name='Acima da CU'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='loquios',
            field=models.CharField(choices=[('fisiologicos', 'fisiologicos'), ('Aumentados', 'Aumentados'), ('fétido', 'fétido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='loquios_aumentados_quantidade',
            field=models.CharField(default='', max_length=30, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='mamas',
            field=models.CharField(choices=[('Flácidas', 'Flácidas'), ('Túrgidas', 'Túrgidas'), ('Ingurgitadas', 'Ingurgitadas'), ('Outros', 'Outros')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='mamilos',
            field=models.CharField(choices=[('Protusos', 'Protusos'), ('Semi-protusos', 'Semi-protusos'), ('Planos', 'Planos'), ('Invertidos', 'Invertidos'), ('Íntegros', 'Íntegros'), ('Fissura', 'Fissura')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='membros_inferiores',
            field=models.CharField(choices=[('Sem alterações', 'Sem alterações'), ('Edema', 'Edema'), ('Varizes', 'Varizes'), ('Deambulante', 'Deambulante')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='nivel_consciencia',
            field=models.CharField(choices=[('Lúcida', 'Lúcida'), ('Orientada', 'Orientada'), ('Desorientada/confusa', 'Desorientada/confusa'), ('Sonolenta', 'Sonolenta'), ('Outros:', 'Outros:')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='nivel_consciencia_outros',
            field=models.CharField(default='', max_length=30, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='pa',
            field=models.CharField(default='', max_length=30, verbose_name='PA'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='pele_mucosa',
            field=models.CharField(choices=[('Corada', 'Corada'), ('Hipocorada', 'Hipocorada'), ('Ictérica', 'Ictérica'), ('Outros', 'Outros')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='pele_mucosa_outros',
            field=models.CharField(default='', max_length=30, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='perdas_vaginais_caracteristicas',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='perineo',
            field=models.CharField(choices=[('Integro', 'Integro'), ('Lacerado', 'Lacerado'), ('Edemaciado', 'Edemaciado'), ('Edema', 'Edema'), ('Hematoma', 'Hematoma')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='peso',
            field=models.CharField(default='', max_length=30, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='r',
            field=models.CharField(default='', max_length=30, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='rn',
            field=models.CharField(default='', max_length=30, verbose_name='RN'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='sifilis',
            field=models.CharField(default='', max_length=30, verbose_name='Sífilis'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='sinal_homans',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='sono_repouso',
            field=models.CharField(choices=[('Satisfatório', 'Satisfatório'), ('Insatisfatório', 'Insatisfatório')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='spo2',
            field=models.CharField(default='', max_length=30, verbose_name='SpO2'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='ssvvt',
            field=models.CharField(default='', max_length=30, verbose_name='SSVVT'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='ts_mae',
            field=models.CharField(default='', max_length=30, verbose_name='TS Mãe'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='utero',
            field=models.CharField(choices=[('Contraído', 'Contraído'), ('Atonia', 'Atonia'), ('Hipotônico', 'Hipotônico')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario0301',
            name='questionario03',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario03', verbose_name='Nome do Paciente'),
        ),
    ]
