# Generated by Django 4.2.2 on 2023-06-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0007_questionario0302_questionario0303_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0301',
            name='perineo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
