# Generated by Django 4.2.2 on 2023-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0009_remove_questionario0301_abdome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0301',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='questionario0301',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
    ]
