# Generated by Django 4.2.2 on 2023-06-28 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0010_alter_questionario0301_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0301',
            name='questionario03',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario03', verbose_name='Nome do Paciente'),
        ),
    ]
