# Generated by Django 4.2.2 on 2023-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0011_alter_questionario0301_questionario03'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario0301',
            name='abdome',
            field=models.CharField(choices=[('Normotenso e flácio', 'Normotenso e flácio'), ('Globoso', 'Globoso'), ('Distendido', 'Distendido'), ('Doloroso', 'Doloroso')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='aceita_dieta_oferecida',
            field=models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial'), ('Não aceita', 'Não aceita'), ('Zero', 'Zero')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='diurese',
            field=models.CharField(choices=[('Espontânea', 'Espontânea'), ('CVD', 'CVD'), ('CVA', 'CVA')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='diurese_caracteristicas',
            field=models.CharField(default='', max_length=100, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='evacuacoes',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='evacuacoes_n_dias',
            field=models.IntegerField(default=0),
        ),
    ]
