# Generated by Django 4.2.2 on 2023-06-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0013_questionario0301_membros_inferiores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario0301',
            name='amamentacao',
            field=models.CharField(choices=[('Satisfatória', 'Satisfatória'), ('Dificuldades', 'Dificuldades'), ('Dor', 'Dor'), ('Pega', 'Pega'), ('Sucção', 'Sucção'), ('Ordenha manual', 'Ordenha manual')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='amamentacao_motivos',
            field=models.CharField(default='', max_length=30, verbose_name='Motivos'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='atura',
            field=models.CharField(default='', max_length=30, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='colostro_expresssao',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Diminuído', 'Diminuído')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='exames_alterados',
            field=models.CharField(default='', max_length=30, verbose_name='Exames Alterados'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='fc',
            field=models.CharField(default='', max_length=30, verbose_name='FC'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='hgt',
            field=models.CharField(default='', max_length=30, verbose_name='HGT'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='higiene',
            field=models.CharField(choices=[('Preservada', 'Preservada'), ('Alterada', 'Alterada')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='inicisao_cirurgica',
            field=models.CharField(choices=[('curativo oclusivo', 'curativo oclusivo'), ('limpa e seca', 'limpa e seca'), ('Com sinais flogísticos', 'Com sinais flogísticos')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='inicisao_cirurgica_quais',
            field=models.CharField(default='', max_length=30, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='involucao_uterina',
            field=models.CharField(choices=[('acima da CU', 'acima da CU'), ('à altura da CU', 'à altura da CU'), ('abaixo da CU', 'abaixo da CU')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='involucao_uterina_acima_cu',
            field=models.CharField(default='', max_length=30, verbose_name='Acima da CU'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='loquios',
            field=models.CharField(choices=[('fisiologicos', 'fisiologicos'), ('Aumentados', 'Aumentados'), ('fétido', 'fétido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='loquios_aumentados_quantidade',
            field=models.CharField(default='', max_length=30, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='mamas',
            field=models.CharField(choices=[('Flácidas', 'Flácidas'), ('Túrgidas', 'Túrgidas'), ('Ingurgitadas', 'Ingurgitadas'), ('Outros', 'Outros')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='mamilos',
            field=models.CharField(choices=[('Protusos', 'Protusos'), ('Semi-protusos', 'Semi-protusos'), ('Planos', 'Planos'), ('Invertidos', 'Invertidos'), ('Íntegros', 'Íntegros'), ('Fissura', 'Fissura')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='nivel_consciencia',
            field=models.CharField(choices=[('Lúcida', 'Lúcida'), ('Orientada', 'Orientada'), ('Desorientada/confusa', 'Desorientada/confusa'), ('Sonolenta', 'Sonolenta'), ('Outros:', 'Outros:')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='nivel_consciencia_outros',
            field=models.CharField(default='', max_length=30, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='pa',
            field=models.CharField(default='', max_length=30, verbose_name='PA'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='pele_mucosa',
            field=models.CharField(choices=[('Corada', 'Corada'), ('Hipocorada', 'Hipocorada'), ('Ictérica', 'Ictérica'), ('Outros', 'Outros')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='pele_mucosa_outros',
            field=models.CharField(default='', max_length=30, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='perdas_vaginais_caracteristicas',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='perineo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='peso',
            field=models.CharField(default='', max_length=30, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='r',
            field=models.CharField(default='', max_length=30, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='rn',
            field=models.CharField(default='', max_length=30, verbose_name='RN'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='sifilis',
            field=models.CharField(default='', max_length=30, verbose_name='Sífilis'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='spo2',
            field=models.CharField(default='', max_length=30, verbose_name='SpO2'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='ssvvt',
            field=models.CharField(default='', max_length=30, verbose_name='SSVVT'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='ts_mae',
            field=models.CharField(default='', max_length=30, verbose_name='TS Mãe'),
        ),
        migrations.AddField(
            model_name='questionario0301',
            name='utero',
            field=models.CharField(choices=[('Contraído', 'Contraído'), ('Atonia', 'Atonia'), ('Hipotônico', 'Hipotônico')], default='', max_length=30),
        ),
    ]
