# Generated by Django 4.2.3 on 2023-07-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0015_questionario0302_questionario03'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0302',
            name='seguranca_emocional',
            field=models.CharField(default='', max_length=200),
        ),
    ]
