# Generated by Django 4.2.3 on 2023-07-04 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0019_alter_questionario0302_seguranca_emocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario0302',
            name='data_atualizacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionario0302',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questionario0302',
            name='questionario03',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario03', verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='questionario0302',
            name='seguranca_emocional',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('alterações de humor', 'Alterações de Humor'), ('Crises de Choro', 'Crises de Choro'), ('Emotividade Exacerbada', 'Emotividade Exacerbada'), ('Insegurança', 'Insegurança'), ('Irritabilidade', 'Irritabilidade'), ('Tristeza', 'Tristeza'), ('Alegria', 'Alegria'), ('Medo', 'Medo'), ('Ansiedade', 'Ansiedade')], default='', max_length=200),
        ),
    ]
