# Generated by Django 4.2.3 on 2023-07-04 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0020_questionario0302_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario0304',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_liquidos_deficiente', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], default='', max_length=30, verbose_name='Volume de Líquidos Deficiente')),
                ('volume_liquidos_deficiente_intervencoes_enfermagem', models.CharField(default='', max_length=30, verbose_name='Intervenções de Enfermagem')),
                ('volume_liquidos_deficiente_avaliacao', models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30, verbose_name='Avaliação')),
            ],
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='data_atualizacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questionario0302',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='questionario0302',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
    ]
