# Generated by Django 4.2.3 on 2023-07-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0021_questionario0304_questionario0303_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario030301',
            fields=[
                ('questionario0303_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionario.questionario0303')),
                ('avaliacao', models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30, verbose_name='Avaliação')),
            ],
            bases=('questionario.questionario0303',),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
    ]
