# Generated by Django 4.2.3 on 2023-07-20 18:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0022_questionario030301_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario0303',
            name='volume_liquidos_deficiente',
        ),
        migrations.RemoveField(
            model_name='questionario0303',
            name='volume_liquidos_deficiente_avaliacao',
        ),
        migrations.RemoveField(
            model_name='questionario0303',
            name='volume_liquidos_deficiente_intervencoes_enfermagem',
        ),
        migrations.RemoveField(
            model_name='questionario0304',
            name='volume_liquidos_deficiente',
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_01',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monitorar o estado de hidratação, conforme apropriado', '1'), ('Oferecer líquidos, conforme apropriado', '2'), ('Monitorar os sinais vitais', '3'), ('Administrar terapia IV, conforme prescrição', '4')], default='', max_length=200, verbose_name='Intervenções de Enfermagem'),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_02',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Informar sobre as vantagens e as desvantagens do aleitamento materno', '1'), ('Corrigir conceitos errados, informações incorretas e imprecisões sobre a amamentação', '2'), ('Monitorar e estimular amamentação sob livre demanda', '3'), ('Avaliar o padrão de sucção/deglutição do recém-nascido', '4')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_03',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Evitar interrupções desnecessárias e permitir períodos de descanso', '1'), ('Criar um ambiente calmo e de apoio', '2'), ('Proporcionar um ambiente seguro e limpo', '3')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_04',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Descrever as razões para o relaxamento, seus benefícios, limites e tipos disponíveis', '1'), ('Criar um ambiente calmo e sem interrupções, com iluminação difusa e temperatura confortável, sempre que possível', '2'), ('Otimizar tempo de internação', '3')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_05',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monitorar a integridade da pele dos mamilos', '1'), ('Orientar sobre o cuidado dos mamilos, inclusive como evitar fissuras', '2'), ('Aplicação de compressa de gelo na região perineal', '3')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_06',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Examinar o local da incisão quanto a hiperemia, edema ou sinais de deiscência', '1'), ('Realizar curativo mantendo rigor asséptico', '2'), ('Aplicar curativo apropriado para proteger a incisão', '3')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_07',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Realizar uma avaliação completa da dor, incluindo local, características, início/duração, frequência, qualidade, intensidade e gravidade, além de fatores precipitadores', '1'), ('Oferecer alívio da dor mediante a analgesia prescrita', '2'), ('Ensinar o uso de técnicas não farmacológicas', '3')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_08',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Usar abordagem calma e tranquilizadora', '1'), ('Observar sinais verbais e não verbais de ansiedade', '2'), ('Encorajar a expressão de sentimentos, percepções e medos', '3'), ('Escutar o paciente com atenção', '4'), ('Explicar todos os procedimentos', '5'), ('Oferecer informações reais sobre diagnóstico, tratamento e prognóstico', '6')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_09',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Discutir os sentimentos que a mãe possa ter em relação ao bebê', '1'), ('Demonstrar confiança na capacidade da mãe para cuidar do recém-nascido', '2'), ('Monitorar o surgimento de sintomas de depressão pós-parto', '3')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_10',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Determinar as necessidades de aprendizagem do paciente', '1'), ('Orientar os pais/cuidador a alimentar somente com leite materno', '2'), ('Orientar os pais/cuidador a colocar o bebê de costas para dormir', '3'), ('Orientar os pais/cuidador a testar a temperatura da água do banho', '4')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Volume de Líquidos Deficiente', '1'), ('Disposição para amamentação melhorada', '2'), ('Privação de sono', '3'), ('Padrão do sono prejudicado', '4'), ('Conforto prejudicado', '5'), ('Integridade da pele prejudicada', '6'), ('Risco de infecção', '7'), ('Dor aguda', '8'), ('Ansiedade', '9'), ('Medo', '10'), ('Disposição para processo perinatológico melhorado', '11'), ('Processo perinatológico ineficaz', '12'), ('Disposição para conhecimento melhorado', '13'), ('Conhecimento deficiente', '14'), ('Outro', '15')], default='', max_length=200, verbose_name='Volume de Líquidos Deficiente'),
        ),
        migrations.DeleteModel(
            name='Questionario030301',
        ),
    ]
