# Generated by Django 4.2.3 on 2023-07-20 18:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0023_remove_questionario0303_volume_liquidos_deficiente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario0303',
            old_name='choices_intervencoes_enfermagem_04',
            new_name='intervencoes_enfermagem_04',
        ),
        migrations.RenameField(
            model_name='questionario0303',
            old_name='choices_intervencoes_enfermagem_05',
            new_name='intervencoes_enfermagem_05',
        ),
        migrations.RenameField(
            model_name='questionario0303',
            old_name='choices_intervencoes_enfermagem_06',
            new_name='intervencoes_enfermagem_06',
        ),
        migrations.RenameField(
            model_name='questionario0303',
            old_name='choices_intervencoes_enfermagem_07',
            new_name='intervencoes_enfermagem_07',
        ),
        migrations.RenameField(
            model_name='questionario0303',
            old_name='choices_intervencoes_enfermagem_08',
            new_name='intervencoes_enfermagem_08',
        ),
        migrations.RenameField(
            model_name='questionario0303',
            old_name='choices_intervencoes_enfermagem_09',
            new_name='intervencoes_enfermagem_09',
        ),
        migrations.RenameField(
            model_name='questionario0303',
            old_name='choices_intervencoes_enfermagem_10',
            new_name='intervencoes_enfermagem_10',
        ),
        migrations.RemoveField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_01',
        ),
        migrations.RemoveField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_02',
        ),
        migrations.RemoveField(
            model_name='questionario0303',
            name='choices_intervencoes_enfermagem_03',
        ),
        migrations.RemoveField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem',
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_01',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Volume de Líquidos Deficiente', 'Volume de Líquidos Deficiente')], default='', max_length=200, verbose_name='Diagnósticos de Enfermagem'),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_02',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Disposição para amamentação melhorada', 'Disposição para amamentação melhorada')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_03',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Privação de sono', 'Privação de sono'), ('Padrão do sono prejudicado', 'Padrão do sono prejudicado')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_04',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Conforto prejudicado', 'Conforto prejudicado')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_05',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Integridade da pele prejudicada', 'Integridade da pele prejudicada')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_06',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Risco de infecção', 'Risco de infecção')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_07',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dor aguda', 'Dor aguda')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_08',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ansiedade', 'Ansiedade'), ('Medo', 'Medo')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_09',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Disposição para processo perinatológico melhorado', 'Disposição para processo perinatológico melhorado'), ('Processo perinatológico ineficaz', 'Processo perinatológico ineficaz')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_10',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Disposição para conhecimento melhorado', 'Disposição para conhecimento melhorado'), ('Conhecimento deficiente', 'Conhecimento deficiente')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='diagnosticos_enfermagem_11',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Outro', 'Outro')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_01',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monitorar o estado de hidratação, conforme apropriado', 'Monitorar o estado de hidratação, conforme apropriado'), ('Oferecer líquidos, conforme apropriado', 'Oferecer líquidos, conforme apropriado'), ('Monitorar os sinais vitais', 'Monitorar os sinais vitais'), ('Administrar terapia IV, conforme prescrição', 'Administrar terapia IV, conforme prescrição')], default='', max_length=200, verbose_name='Intervenções de Enfermagem'),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_02',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Informar sobre as vantagens e as desvantagens do aleitamento materno', 'Informar sobre as vantagens e as desvantagens do aleitamento materno'), ('Corrigir conceitos errados, informações incorretas e imprecisões sobre a amamentação', 'Corrigir conceitos errados, informações incorretas e imprecisões sobre a amamentação'), ('Monitorar e estimular amamentação sob livre demanda', 'Monitorar e estimular amamentação sob livre demanda'), ('Avaliar o padrão de sucção/deglutição do recém-nascido', 'Avaliar o padrão de sucção/deglutição do recém-nascido')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_03',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Evitar interrupções desnecessárias e permitir períodos de descanso', 'Evitar interrupções desnecessárias e permitir períodos de descanso'), ('Criar um ambiente calmo e de apoio', 'Criar um ambiente calmo e de apoio'), ('Proporcionar um ambiente seguro e limpo', 'Proporcionar um ambiente seguro e limpo')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_11',
            field=models.TextField(default='', max_length=2000, verbose_name=''),
        ),
    ]
