# Generated by Django 4.2.3 on 2023-07-20 19:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0024_rename_choices_intervencoes_enfermagem_04_questionario0303_intervencoes_enfermagem_04_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_01',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_02',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_03',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_04',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_05',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_06',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_07',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_08',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_09',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_10',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionario0303',
            name='avaliacao_11',
            field=models.CharField(choices=[('Melhorado', 'Melhorado'), ('Piorado', 'Piorado'), ('Inalterado', 'Inalterado'), ('Resolvido', 'Resolvido')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_04',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Descrever as razões para o relaxamento, seus benefícios, limites e tipos disponíveis', 'Descrever as razões para o relaxamento, seus benefícios, limites e tipos disponíveis'), ('Criar um ambiente calmo e sem interrupções, com iluminação difusa e temperatura confortável, sempre que possível', 'Criar um ambiente calmo e sem interrupções, com iluminação difusa e temperatura confortável, sempre que possível'), ('Otimizar tempo de internação', 'Otimizar tempo de internação')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_05',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monitorar a integridade da pele dos mamilos', 'Monitorar a integridade da pele dos mamilos'), ('Orientar sobre o cuidado dos mamilos, inclusive como evitar fissuras', 'Orientar sobre o cuidado dos mamilos, inclusive como evitar fissuras'), ('Aplicação de compressa de gelo na região perineal', 'Aplicação de compressa de gelo na região perineal')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_06',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Examinar o local da incisão quanto a hiperemia, edema ou sinais de deiscência', 'Examinar o local da incisão quanto a hiperemia, edema ou sinais de deiscência'), ('Realizar curativo mantendo rigor asséptico', 'Realizar curativo mantendo rigor asséptico'), ('Aplicar curativo apropriado para proteger a incisão', 'Aplicar curativo apropriado para proteger a incisão')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_07',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Realizar uma avaliação completa da dor, incluindo local, características, início/duração, frequência, qualidade, intensidade e gravidade, além de fatores precipitadores', 'Realizar uma avaliação completa da dor, incluindo local, características, início/duração, frequência, qualidade, intensidade e gravidade, além de fatores precipitadores'), ('Oferecer alívio da dor mediante a analgesia prescrita', 'Oferecer alívio da dor mediante a analgesia prescrita'), ('Ensinar o uso de técnicas não farmacológicas', 'Ensinar o uso de técnicas não farmacológicas')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_08',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Usar abordagem calma e tranquilizadora', 'Usar abordagem calma e tranquilizadora'), ('Observar sinais verbais e não verbais de ansiedade', 'Observar sinais verbais e não verbais de ansiedade'), ('Encorajar a expressão de sentimentos, percepções e medos', 'Encorajar a expressão de sentimentos, percepções e medos'), ('Escutar o paciente com atenção', 'Escutar o paciente com atenção'), ('Explicar todos os procedimentos', 'Explicar todos os procedimentos'), ('Oferecer informações reais sobre diagnóstico, tratamento e prognóstico', 'Oferecer informações reais sobre diagnóstico, tratamento e prognóstico')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_09',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Discutir os sentimentos que a mãe possa ter em relação ao bebê', 'Discutir os sentimentos que a mãe possa ter em relação ao bebê'), ('Demonstrar confiança na capacidade da mãe para cuidar do recém-nascido', 'Demonstrar confiança na capacidade da mãe para cuidar do recém-nascido'), ('Monitorar o surgimento de sintomas de depressão pós-parto', 'Monitorar o surgimento de sintomas de depressão pós-parto')], default='', max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='questionario0303',
            name='intervencoes_enfermagem_10',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Determinar as necessidades de aprendizagem do paciente', 'Determinar as necessidades de aprendizagem do paciente'), ('Orientar os pais/cuidador a alimentar somente com leite materno', 'Orientar os pais/cuidador a alimentar somente com leite materno'), ('Orientar os pais/cuidador a colocar o bebê de costas para dormir', 'Orientar os pais/cuidador a colocar o bebê de costas para dormir'), ('Orientar os pais/cuidador a testar a temperatura da água do banho', 'Orientar os pais/cuidador a testar a temperatura da água do banho')], default='', max_length=200, verbose_name=''),
        ),
    ]
