# Generated by Django 4.2.3 on 2023-07-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0028_alter_questionario0303_questionario03_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario0303',
            name='questionario03',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario03', verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='questionario0304',
            name='questionario03',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario03', verbose_name='Nome do Paciente'),
        ),
    ]
