# Generated by Django 4.2.3 on 2023-07-28 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("questionario", "0031_questionario05_questionario04"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionario04",
            name="data_atualizacao",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="questionario04",
            name="data_cadastro",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
