# Generated by Django 4.2.3 on 2023-08-01 17:23

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("questionario", "0033_alter_questionario04_data_atualizacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionario05",
            name="a",
            field=models.CharField(default="", max_length=30, verbose_name="A"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="aspecto_liquido",
            field=models.CharField(
                choices=[
                    ("Claro", "Claro"),
                    ("Meconial fluido", "Meconial fluido"),
                    ("Meconial espesso", "Meconial espesso"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="bcf",
            field=models.CharField(default="", max_length=30, verbose_name="BCF"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="contracoes_uterinas",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("Sim", "Sim"), ("Não", "Não")], default="", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="dor",
            field=models.CharField(default="", max_length=30, verbose_name="Dor"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="dum",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="DUM"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="fc",
            field=models.CharField(default="", max_length=30, verbose_name="FC"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="fr",
            field=models.CharField(default="", max_length=30, verbose_name="FR"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="g",
            field=models.CharField(default="", max_length=30, verbose_name="G"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="hipertonia_uterina",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")], default="", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="hora_atendimento_nome_medico_avaliador",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Horário"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="hora_atendimento_profissional_enfermagem_coren",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Horário"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="horario_chegada",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Horário"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="horario_classficacao",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Horário"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="localizacao",
            field=models.CharField(
                default="", max_length=30, verbose_name="Localização"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="medicamentos_uso_gravidez",
            field=models.CharField(
                default="",
                max_length=30,
                verbose_name="Medicamentos em uso na gravidez",
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="mf",
            field=models.CharField(default="", max_length=30, verbose_name="MF"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="nome_medico_avaliador",
            field=models.CharField(
                default="", max_length=30, verbose_name="Nome do Médico Avaliador"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="observacoes",
            field=models.CharField(
                choices=[
                    ("Alergias", "Alergias"),
                    ("Drogas", "Drogas"),
                    ("Outras", "Outras"),
                ],
                default="",
                max_length=30,
                verbose_name="Observações",
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="outras_queixas_relatos",
            field=models.CharField(
                default="", max_length=30, verbose_name="Outras Queixas e/ou relatos"
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="p",
            field=models.CharField(default="", max_length=30, verbose_name="P"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="pa",
            field=models.CharField(default="", max_length=30, verbose_name="PA"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="perda_liquido",
            field=models.CharField(
                choices=[("Sim", "Sim"), ("Não", "Não")], default="", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="profissional_enfermagem_coren",
            field=models.CharField(
                default="",
                max_length=30,
                verbose_name="Profissional de Enfermagem (COREN)",
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="queixas",
            field=models.CharField(default="", max_length=30, verbose_name="Queixas"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="sangramento_vaginal",
            field=models.CharField(
                choices=[("Ausente", "Ausente"), ("Presente", "Presente")],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="sato2",
            field=models.CharField(default="", max_length=30, verbose_name="SatO2"),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="temp",
            field=models.CharField(default="", max_length=30, verbose_name="Temp"),
        ),
        migrations.AlterField(
            model_name="questionario0303",
            name="intervencoes_enfermagem_07",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (
                        "Realizar uma avaliação completa da dor, incluindo local, características, início/duração, frequência,qualidade, intensidade e gravidade, além de fatores precipitadores",
                        "Realizar uma avaliação completa da dor, incluindo local, características, início/duração, frequência,qualidade, intensidade e gravidade, além de fatores precipitadores",
                    ),
                    (
                        "Oferecer alívio da dor mediante a analgesia prescrita",
                        "Oferecer alívio da dor mediante a analgesia prescrita",
                    ),
                    (
                        "Ensinar o uso de técnicas não farmacológicas",
                        "Ensinar o uso de técnicas não farmacológicas",
                    ),
                ],
                default="",
                max_length=200,
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="questionario0304",
            name="check_list_enfermagem_alta_hospitalar",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (
                        "Puérpera recebeu e compreendeu as informações sobre cuidados com RN, autocuidado, aleitameto materno e retorno a sua unidade de saúde na primeira semana de vida da criança para consulta puerperal",
                        "Puérpera recebeu e compreendeu as informações sobre cuidados com RN, autocuidado, aleitameto materno eretorno a sua unidade de saúde na primeira semana de vida da criança para consulta puerperal",
                    ),
                    (
                        "RN em AME com sucção ao seio, pega e posicionamento adequados, pois NÃO há restrições ao aleitamento materno",
                        "RN em AME com sucção ao seio, pega e posicionamento adequados, pois NÃO há restrições ao aleitamento materno",
                    ),
                    (
                        "RN em uso de substituto do leite humano/formula láctea pois a amamentação é contra-indicada de acordo com atualização OMS",
                        "RN em uso de substituto do leite humano/formula láctea pois a amamentação é contra-indicada de acordo com atualização OMS",
                    ),
                    (
                        "A mãe, o pai e outros cuidadores foram orientados a reconhecer situações de risco e a procurar a USF se o recémnascido apresentar problemas com aleitamento materno, icterícia ou qualquer outra alteração",
                        "A mãe, o pai e outros cuidadores foram orientados a reconhecer situações de risco e a procurar a USF se o recémnascido apresentar problemas com aleitamento materno, icterícia ou qualquer outra alteração",
                    ),
                    (
                        "A mulher foi orientada a procurar a USF ou o hospital caso apresente febre, secreção purulenta vaginal, por ferida operatória, sangramento com odor fétido ou com volume aumentado, edema assimétrico de extremidades, sofrimento emocional ou outros desconfortos, intercorrências com as mamas",
                        "A mulher foi orientada a procurar a USF ou o hospital caso apresente febre, secreção purulenta vaginal, por ferida operatória, sangramento com odor fétido ou com volume aumentado, edema assimétrico de extremidades, sofrimento emocional ou outros desconfortos, intercorrências com as mamas",
                    ),
                    (
                        "Orientada a higienizar as mãos antes e após o cuidado com o recém-nascido",
                        "Orientada a higienizar as mãos antes e após o cuidado com o recém-nascido",
                    ),
                    (
                        "Orientada a deixar a criança em decúbito dorsal, manter a amamentação ao seio até os 6 meses exclusivamente e 2 anos ou mais complementar",
                        "Orientada a deixar a criança em decúbito dorsal, manter a amamentação ao seio até os 6 meses exclusivamente e 2 anos ou mais complementar",
                    ),
                    (
                        "Alta hospitalar evoluida no prontuário, dados do RN anotado na carteira da criança",
                        "Alta hospitalar evoluida no prontuário, dados do RN anotado na carteira da criança",
                    ),
                    (
                        "Solicitado avaliação do serviço social se necessário",
                        "Solicitado avaliação do serviço social se necessário",
                    ),
                ],
                default="",
                max_length=5000,
                verbose_name="Check List de Enfermagem para Alta Hospitalar",
            ),
        ),
    ]
