# Generated by Django 4.2.3 on 2023-08-02 18:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "questionario",
            "0034_questionario05_a_questionario05_aspecto_liquido_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionario05",
            name="contracoes_uterinas",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("Sim", "Sim"), ("Não", "Não")],
                default="",
                max_length=30,
                verbose_name="Contrações Uterinas",
            ),
        ),
    ]
