# Generated by Django 4.2.3 on 2023-09-22 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("questionario", "0036_alter_questionario04_dinamica_uterina_tempo"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionario05",
            name="data_atualizacao",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="questionario05",
            name="data_cadastro",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
