# Generated by Django 4.2.2 on 2023-06-23 21:16

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(default='', max_length=14)),
                ('nome', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField(default='')),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], default='', max_length=100)),
                ('profissao_ocupacao', models.CharField(default='', max_length=100)),
                ('raca', models.CharField(choices=[('Pardo', 'Pardo'), ('Branco', 'Branco'), ('Preto', 'Preto'), ('Amarelo', 'Amarelo'), ('Indígena', 'Indígena')], default='', max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
