# Generated by Django 4.2.2 on 2023-06-25 16:56

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=cpf_field.models.CPFField(default='', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default='', verbose_name='data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profissao_ocupacao',
            field=models.CharField(default='', max_length=100, verbose_name='Profissão/Ocupação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='raca',
            field=models.CharField(choices=[('Pardo', 'Pardo'), ('Branco', 'Branco'), ('Preto', 'Preto'), ('Amarelo', 'Amarelo'), ('Indígena', 'Indígena')], default='', max_length=20, verbose_name='Raça'),
        ),
    ]
