# Generated by Django 4.2.3 on 2023-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0002_alter_usuario_cpf_alter_usuario_data_nascimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="escolaridade",
            field=models.CharField(
                choices=[
                    ("Fundamental - incompleto", "Fundamental - incompleto"),
                    ("Fundamental - completo", "Fundamental - completo"),
                    ("Médio - incompleto", "Médio - incompleto"),
                    ("Médio - completo", "Médio - completo"),
                    ("Superior - incompleto", "Superior - incompleto"),
                    ("Superior - completo", "Superior - completo"),
                    ("Pós-graduação - incompleto", "Pós-graduação - incompleto"),
                    ("Pós-graduação - completo", "Pós-graduação - completo"),
                    ("Mestrado - incompleto", "Mestrado - incompleto"),
                    ("Mestrado - completo", "Mestrado - completo"),
                    ("Doutorado - incompleto", "Doutorado - incompleto"),
                    ("Doutorado - completo", "Doutorado - completo"),
                    ("Pós-doutorado - incompleto", "Pós-doutorado - incompleto"),
                    ("Pós-doutorado - completo", "Pós-doutorado - completo"),
                    ("Não se aplica", "Não se aplica"),
                    ("Não informado", "Não informado"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
